# Generated by Django 3.0.14 on 2021-06-06 07:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('serial_no', models.TextField(unique=True)),
                ('secret_key', models.TextField()),
                ('mac_address', models.TextField()),
                ('sensor_type', models.CharField(choices=[('wall_mount', 'WALL_MOUNT'), ('outdoor', 'OUTDOOR'), ('ceiling_mount', 'CEILING_MOUNT')], default='ceiling_mount', max_length=30)),
                ('manufacturer', models.TextField()),
                ('stored_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
